import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(component)/Navbar";
import Footer from "./(component)/Footer";
import MainHome from "./(component)/MainHome";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Slicing Sagara Asia Teknologi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MainHome />
        {children}
        <Footer />
      </body>
    </html>
  );
}
